### PR TITLE
Main

### PR DESCRIPTION
**Pull request by luiscast84**
Enabled compatibility with latest versions of Paho:
# Check if CallbackAPIVersion is available (newer paho-mqtt versions)
    if hasattr(paho, 'CallbackAPIVersion'):
        client = paho.Client(paho.CallbackAPIVersion.VERSION1, client_id)
    else:
        # For older paho-mqtt versions
        client = paho.Client(client_id)

### CODE REVIEW

**Comment by nabeelmsft** [comment]
Looks good. Thanks for the update!

**Review by nabeelmsft — APPROVED** [review]
Looks great. Thank you!

**Comment by luiscast84** [comment]
[heart]         Luis Castillo Lopez reacted to your message:
________________________________

**Comment by luiscast84** [comment]
There is a second commit to this PR. Is that something you approve it? @nabeelmsft

**Pull request merged**
